### Pivoting

#### Deklarasi library

In [1]:
import numpy as np
import logging

In [2]:
logging.basicConfig (level=logging.ERROR)
logging.error ('Matrix is singular')

ERROR:root:Matrix is singular


In [3]:
def tukarBaris (matrix, row1, row2):
    matrix[[row1, row2]] = matrix[[row2, row1]]

In [4]:
a = np.array ([[1,2,3], [3,4,2], [7,7,5]])
print (f"a\n {a} \n\n")
tukarBaris (a, 1, 2)
print (f"a\n {a}")

a
 [[1 2 3]
 [3 4 2]
 [7 7 5]] 


a
 [[1 2 3]
 [7 7 5]
 [3 4 2]]


#### Fungsi Decomposition

In [5]:
def Decom (matA, nilai_toleransi):
    panjang_mat = len (matA)
    urutan = np.array (range (panjang_mat))

    # buat faktor skala
    faktor_skala = np.zeros ((panjang_mat))
    # cek nilai terbesar dari tiap baris
    for s in range (panjang_mat):
        faktor_skala[s] = max (abs (matA[s,:]))
    #print (f"s \n {faktor_skala}\n\n")

    for k in range (0, panjang_mat-1):
        
        # menentukan index keberapa yang memiliki nilai terbesar
        p = np.argmax (np.abs (matA[k:panjang_mat, k]) / faktor_skala[k:panjang_mat]) + k
        #print (f"p = {p} | k = {k} | A[p,k] = {matA[p,k]}")

        if abs(matA[p,k]) <  nilai_toleransi: logging.error('Matrix is singular')
        
        if p != k:
           tukarBaris (faktor_skala, k, p)
           tukarBaris (matA, k, p)
           tukarBaris (urutan, k, p)

     # Elimination
        for i in range(k+1,panjang_mat):
            if matA[i,k] != 0.0:
                lam = matA[i,k] / matA[k,k]
                matA[i,k+1:panjang_mat] = matA[i,k+1:panjang_mat] - lam*matA[k,k+1:panjang_mat]
                matA[i,k] = lam

    return matA, urutan

#### Fungsi Solve

In [11]:
def Solve (matA, matB, urutan):
    panjang_mat = len (matA)

    # atur urutan konstanta 
    y = matB.copy()
    #print (f"y \n {y}")
    
    for i in range (panjang_mat):
        y[i] = matB[urutan[i]]
    #print (f"y \n {y}")

    # Solution
    for k in range (1, panjang_mat):
        y[k] = y[k] - np.dot (matA[k,0:k], y[0:k])
        #print (f"y[{k}] = {y[k]}")
    y[panjang_mat-1] = y[panjang_mat-1] / matA[panjang_mat-1, panjang_mat-1]
    
    #print (y)

    for k in range (panjang_mat-2, -1, -1):  # range (start, stop, step)
       y[k] = (y[k] - np.dot(matA[k, k+1:panjang_mat], y[k+1:panjang_mat])) / matA[k, k]
       #print (f"\ny[{k}] = {y[k]}")

    return y 

#### Contoh kasus

In [7]:
a = np.array ([[2, -2, 6], 
               [-2, 4, 3], 
               [-1, 8, 4]])
print (a)

[[ 2 -2  6]
 [-2  4  3]
 [-1  8  4]]


In [8]:
b = np.array ([[16],
               [0], 
               [1]])
print (b)

[[16]
 [ 0]
 [ 1]]


In [9]:
a, seq = Decom (a, 1.0e-9)
print (f"\nA = \n {a} \n\n seq = \n {seq}")


A = 
 [[-2  4  3]
 [ 0  6  2]
 [-1  0  8]] 

 seq = 
 [1 2 0]


In [12]:
y = Solve (a, b, seq)
print (f"Hasil Y\n {y}")

Hasil Y
 [[3]
 [0]
 [2]]
